//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlineShop.Common.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10001.
        /// </summary>
        public static string ACCOUNT_HAS_REGISTERED {
            get {
                return ResourceManager.GetString("ACCOUNT_HAS_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account has been registered.
        /// </summary>
        public static string ACCOUNT_HAS_REGISTERED_MSG {
            get {
                return ResourceManager.GetString("ACCOUNT_HAS_REGISTERED_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10005.
        /// </summary>
        public static string BRAND_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("BRAND_ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The brand has already existed.
        /// </summary>
        public static string BRAND_ALREADY_EXIST_MSG {
            get {
                return ResourceManager.GetString("BRAND_ALREADY_EXIST_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10004.
        /// </summary>
        public static string BRAND_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("BRAND_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The brand does not exist.
        /// </summary>
        public static string BRAND_DOES_NOT_EXIST_MSG {
            get {
                return ResourceManager.GetString("BRAND_DOES_NOT_EXIST_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10006.
        /// </summary>
        public static string CATEGORY_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("CATEGORY_ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category has already existed.
        /// </summary>
        public static string CATEGORY_ALREADY_EXIST_MSG {
            get {
                return ResourceManager.GetString("CATEGORY_ALREADY_EXIST_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10002.
        /// </summary>
        public static string DEVICE_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("DEVICE_ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device has already existed.
        /// </summary>
        public static string DEVICE_ALREADY_EXIST_MSG {
            get {
                return ResourceManager.GetString("DEVICE_ALREADY_EXIST_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10003.
        /// </summary>
        public static string DEVICE_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("DEVICE_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device does not exist.
        /// </summary>
        public static string DEVICE_DOES_NOT_EXIST_MSG {
            get {
                return ResourceManager.GetString("DEVICE_DOES_NOT_EXIST_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10007.
        /// </summary>
        public static string PRODUCT_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("PRODUCT_ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product has already existed.
        /// </summary>
        public static string PRODUCT_ALREADY_EXIST_MSG {
            get {
                return ResourceManager.GetString("PRODUCT_ALREADY_EXIST_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10000.
        /// </summary>
        public static string USERNAME_PASSWORD_DO_NOT_CORRECT {
            get {
                return ResourceManager.GetString("USERNAME_PASSWORD_DO_NOT_CORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password do not correct.
        /// </summary>
        public static string USERNAME_PASSWORD_DO_NOT_CORRECT_MSG {
            get {
                return ResourceManager.GetString("USERNAME_PASSWORD_DO_NOT_CORRECT_MSG", resourceCulture);
            }
        }
    }
}
